### ISSUE TITLE
non-Ascii in MathML not parsing

### ISSUE THREAD

**Issue by opoudjis** [plurimath/plurimath#104]
Plurimath::Math.parse(x, "mathml") raises a parsing error if x is any of:

````
<math><mi>α</mi></math>
<math><mi>&#x3b1;</mi></math>
<math><mi>&#945;</mi></math>
````

This indicates to me that the parser of MathML is being limited to Ascii.

Asciimath and Latex by design as ascii-only. MathML as input necessarily is not.

**Comment by suleman-uzair** [comment]
@opoudjis https://github.com/plurimath/plurimath/issues/103#issuecomment-1383602953

**Comment by opoudjis** [comment]
Converts correctly to 

````
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
<mstyle displaystyle="true"><mi>&#x3b1;</mi></mstyle>
</math>
````
