### ISSUE TITLE
Add auto-release Ruby gems workflow

### ISSUE THREAD

**Issue by ronaldtse** [plurimath/plurimath#106]

**Comment by suleman-uzair** [comment]
@ronaldtse, I think I need your help to complete the GitHub Action. Please update the [ci gem](https://github.com/metanorma/ci/commit/6b24b80c9715374eeb669f13744adfa6fae9fe9b) for GitHub Action to work properly.

**Comment by CAMOBAP** [comment]
@ronaldtse @suleman-uzair can you confirm that we have `secrets.METANORMA_CI_PAT_TOKEN` in this organization?

If not we need to create `METANORMA_CI_PAT_TOKEN` or `PLURIMATH_CI_PAT_TOKEN` and `METANORMA_CI_RUBYGEMS_API_KEY` or `PLURIMATH_CI_RUBYGEMS_API_KEY`

**Comment by ronaldtse** [comment]
We do have:
<img width="352" alt="Screen Shot 2023-01-18 at 8 09 42 PM" src="https://user-images.githubusercontent.com/11865/213167916-2d8cb2a7-31dd-48f6-a0de-c55afd21d94e.png">

And I believe we have added all the gems to the plurimath Rubygems account for publication purposes.

**Comment by CAMOBAP** [comment]
@ronaldtse Thanks, I will create a separate support repository in plurimath to keep all CI configuration

**Comment by CAMOBAP** [comment]
@ronaldtse could you please give me write access for https://github.com/plurimath/html2asciimath

**Comment by ronaldtse** [comment]
> @ronaldtse could you please give me write access for https://github.com/plurimath/html2asciimath

Done.

**Comment by CAMOBAP** [comment]
@ronaldtse @suleman-uzair all gem repos in plurimath now reuse workflows from https://github.com/plurimath/support

Please go ahead and try auto-release workflow.

In case of any issues feel free to report a ticket in https://github.com/plurimath/support to me
