### ISSUE TITLE
(URGENT) BIPM SI Brochure: explicit parentheses are not shown

### ISSUE THREAD

**Issue by ronaldtse** [plurimath/plurimath#133]
Reported by @manuelfuenmayor at https://github.com/metanorma/bipm-si-brochure/pull/213#issuecomment-1513871484:

There are a few cases where parentheses are not shown, for instance:
   Generated French version:
   ![brochure-issue-7-fr](https://user-images.githubusercontent.com/33627611/232919394-b74f49e3-9926-424d-98b8-bf6308b8b70c.PNG)
  
   Original:
   ![brochure-issue-7-fr-original](https://user-images.githubusercontent.com/33627611/232919415-d67999a3-70e5-446d-83b6-822b3568f5b0.PNG)
    (Please also note the second case, `(X) g/mol`, that I missed to highlight.)

In certain cases we need to show explicit parentheses in a formula. I don't know if we need to make some special syntax to indicate that the parentheses are explicit.

The formula is in AsciiMath:

```adoc
n_"S"("X") = m_"S" // ii(M)("X"), " and " ii(M)(""X"") = ii(A)_"r"("X") "unitsml(g/mol)"
```

**Comment by manuelfuenmayor** [comment]
There are still cases where parentheses get obviated:

Expressions:
````
- (a)_n
- (c)_n
````

Output:
![issue-2-html](https://user-images.githubusercontent.com/33627611/233704109-54a558f2-c3de-4994-8658-5d46e2533361.PNG)

Expected result:
![issue-2-original](https://user-images.githubusercontent.com/33627611/233704198-cc3c7f17-7edd-4574-a16e-1f2f4a0c1afe.PNG)

**Comment by manuelfuenmayor** [comment]
Case above moved to another ticket: https://github.com/plurimath/plurimath/issues/146
Closing.
