### ISSUE TITLE
AsciiMath: Magnitude symbol (`abs(a)`) is not presented as expected

### ISSUE THREAD

**Issue by manuelfuenmayor** [plurimath/plurimath#137]
In relation to https://github.com/metanorma/iso-iec-80000/pull/38

I presume this issue has to do with plurimath:

`stem:[abs(A)]` renders as "abs A", instead of "| A |".

**Comment by manuelfuenmayor** [comment]
The same issue occurs for: `stem:[ceil(x)]`. It is shown as "ceil x", instead of "⌈x⌉"

**Comment by ronaldtse** [comment]
`ceil` moved to https://github.com/plurimath/plurimath/issues/138

**Comment by ronaldtse** [comment]
@suleman-uzair we need to double check if this also happens with other math input syntaxes, e.g. LaTeX.
