### ISSUE TITLE
Parentheses not rendering in exponent expressions

### ISSUE THREAD

**Issue by manuelfuenmayor** [plurimath/plurimath#143]
*Issue found in https://github.com/metanorma/iso-iec-80000/pull/41*

Expression sample:
```adoc
"H"_nu^((1))(z)

"H"_nu^((2))(z)
```

Output:
![issue-3-pdf](https://user-images.githubusercontent.com/33627611/233687730-7b9ef359-558a-41bd-a29c-ddebe0497ded.PNG)

Expected result:
![issue-3-original](https://user-images.githubusercontent.com/33627611/233687793-95ef5bf3-ed81-4e0a-a1d9-1d6413ed411a.PNG)

**Comment by suleman-uzair** [comment]
Fixed in #149
