### ISSUE TITLE
MathML encoding for vertical bar symbol should be in straight type

### ISSUE THREAD

**Issue by manuelfuenmayor** [plurimath/plurimath#144]
*As requested in https://github.com/metanorma/metanorma-standoc/issues/778#issuecomment-1516251046*
*Issue found in https://github.com/metanorma/iso-iec-80000/pull/41*

Currently, vertical bar symbol is encoded in italics: `<mi>∣</mi>`

Maybe it is better to be encoded as `<mo>∣</mo>`.

**Comment by suleman-uzair** [comment]
Fixed in #149
