### ISSUE TITLE
(URGENT) LaTeX math formula parsing crash

### ISSUE THREAD

**Issue by ronaldtse** [plurimath/plurimath#145]
Reported by @jonsneyers:

https://github.com/metanorma/metanorma/issues/290
```
  \\[out_k = \\frac{1}{s}\\left(k == 0 ? 1 : \\sqrt{2}\\right)\\sum_{n = 0}^{s - 1}{in_{n} \\cdot \\cos\\left( \\frac{\\pi k}{s}\\left( n + \\frac{1}{2} \\right) \\right)}\\]
```

@suleman-uzair can you please help fix this ASAP? Thanks.

**Comment by jonsneyers** [comment]
It looks like it seems to struggle with the `\left( expression \right)` construct. Replacing that with just regular brackets (so `( expression )`) makes it parse, but the layout I'm getting when doing that looks weird: the left bracket is smaller than the right bracket and does not match the height that is suitable for `expression`.

**Comment by ronaldtse** [comment]
@jonsneyers thank you for the additional insight. We need to first figure out whether the bracket height mismatch is due to broken MathML encoding or MathML rendering. Will revert.

**Comment by ronaldtse** [comment]
The generated MathML from Plurimath is as follows:

```ruby
> Plurimath::Math.parse('\[out_k = \frac{1}{s} (k == 0 ? 1 : \sqrt{2}) \sum_{n = 0}^{s - 1}{in_{n} \cdot
 \cos( \frac{\pi k}{s} ( n + \frac{1}{2} ) )}\]',:latex).to_mathml
```

```xml
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <mstyle displaystyle="true">
    <mo>[</mo>
    <mi>o</mi>
    <mi>u</mi>
    <msub>
      <mi>t</mi>
      <mi>k</mi>
    </msub>
    <mo>=</mo>
    <mfrac>
      <mn>1</mn>
      <mi>s</mi>
    </mfrac>
    <mo>(</mo>
    <mi>k</mi>
    <mo>=</mo>
    <mo>=</mo>
    <mn>0</mn>
    <mi>?</mi>
    <mn>1</mn>
    <mo>:</mo>
    <msqrt>
      <mn>2</mn>
    </msqrt>
    <mo>)</mo>
    <munderover>
      <mo>&#x2211;</mo>
      <mrow>
        <mi>n</mi>
        <mo>=</mo>
        <mn>0</mn>
      </mrow>
      <mrow>
        <mi>s</mi>
        <mo>&#x2212;</mo>
        <mn>1</mn>
      </mrow>
    </munderover>
    <mrow>
      <mi>i</mi>
      <msub>
        <mi>n</mi>
        <mi>n</mi>
      </msub>
      <mo>&#x22c5;</mo>
      <mrow>
        <mi>cos</mi>
        <mo>(</mo>
      </mrow>
      <mfrac>
        <mrow>
          <mi>&#x3c0;</mi>
          <mi>k</mi>
        </mrow>
        <mi>s</mi>
      </mfrac>
      <mo>(</mo>
      <mi>n</mi>
      <mo>+</mo>
      <mfrac>
        <mn>1</mn>
        <mn>2</mn>
      </mfrac>
      <mo>)</mo>
      <mo>)</mo>
    </mrow>
    <mo>]</mo>
  </mstyle>
</math>
```

Here there is a problem with the parentheses and brackets rendering as `<mo>` instead of `<mfenced>`.

The Mozilla MathML Tester using Safari shows:
https://www-archive.mozilla.org/projects/mathml/demo/tester
<img width="687" alt="Screenshot 2023-04-27 at 1 31 49 PM" src="https://user-images.githubusercontent.com/11865/234768143-064197bf-8125-47c6-8127-e09b623f41cd.png">

MathJax:
https://www.mathjax.org/#demo
<img width="1190" alt="Screenshot 2023-04-27 at 1 32 53 PM" src="https://user-images.githubusercontent.com/11865/234768294-6e51768b-f22f-4928-bf50-0a4aa28e7deb.png">

As you can see because of the `mo` and `mfenced` difference the brackets have different heights. 

i.e. This is a Plurimath parsing / MathML generating issue. Hopefully it is not a rendering issue.

**Comment by ronaldtse** [comment]
Actually I just found out that `mrow` and `mo` are the proper replacements for `mfenced` which is deprecated. Then the problem is because of the grouping via `mrow` within two wrapping `mo`s.

I rephrased the formula slightly to just:
```
out_k = \frac{1}{s} ( k == 0 ? 1 : \sqrt{2} ) \sum_{n = 0}^{s - 1} {in_{n} \cdot \cos ( \frac{\pi k}{s} ( n + \frac{1}{2} ) ) }
```

And the code generated was not too different (same problems):
```ruby
> Plurimath::Math.parse('out_k = \frac{1}{s} ( k == 0 ? 1 : \sqrt{2} ) \sum_{n = 0}^{s - 1} {in_{n} \cdot \cos ( \frac{\pi k}{s} ( n + \frac{1}{2} ) ) }',:latex).to_mathml
```

MathJax:
<img width="1180" alt="Screenshot 2023-04-27 at 1 44 24 PM" src="https://user-images.githubusercontent.com/11865/234770000-dd740a41-48b1-4fbe-8575-1c3de6efcd72.png">

@suleman-uzair : There are a few problems here:

```xml

<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <mstyle displaystyle="true">
    <mi>o</mi>
    <mi>u</mi>
    <msub>
      <mi>t</mi>
      <mi>k</mi>
    </msub>
    <mo>=</mo>
    <mfrac>
      <mn>1</mn>
      <mi>s</mi>
    </mfrac>
    <mo>(</mo>
    <mi>k</mi>
    <mo>=</mo>
    <mo>=</mo>
    <mn>0</mn>
    <mi>?</mi>
    <mn>1</mn>
    <mo>:</mo>
    <msqrt>
      <mn>2</mn>
    </msqrt>
    <mo>)</mo>
    <munderover>
      <mo>&#x2211;</mo>
      <mrow>
        <mi>n</mi>
        <mo>=</mo>
        <mn>0</mn>
      </mrow>
      <mrow>
        <mi>s</mi>
        <mo>&#x2212;</mo>
        <mn>1</mn>
      </mrow>
    </munderover>
    <mrow>
      <mi>i</mi>
      <msub>
        <mi>n</mi>
        <mi>n</mi>
      </msub>
      <mo>&#x22c5;</mo>
      <mrow>
        <mi>cos</mi>
        <mo>(</mo>
      </mrow>
      <mfrac>
        <mrow>
          <mi>&#x3c0;</mi>
          <mi>k</mi>
        </mrow>
        <mi>s</mi>
      </mfrac>
      <mo>(</mo>
      <mi>n</mi>
      <mo>+</mo>
      <mfrac>
        <mn>1</mn>
        <mn>2</mn>
      </mfrac>
      <mo>)</mo>
      <mo>)</mo>
    </mrow>
  </mstyle>
</math>                                               
```

The correct Presentation MathML output should be (@suleman-uzair use this as spec):

```xml
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <mstyle displaystyle="true">
    <mi>o</mi>
    <mi>u</mi>
    <msub>
      <mi>t</mi>
      <mi>k</mi>
    </mrow>
    </msub>
    <mo>=</mo>
    <mfrac>
      <mrow><mn>1</mn></mrow>
      <mrow><mi>s</mi></mrow>
    </mfrac>
    <mo>(</mo>
    <mrow>
      <mi>k</mi>
      <mo>=</mo>
      <mo>=</mo>
      <mn>0</mn>
      <mi>?</mi>
      <mn>1</mn>
      <mo>:</mo>
      <msqrt>
        <mn>2</mn>
      </msqrt>
    </mrow>
    <mo>)</mo>
    <munderover>
      <mo>&#x2211;</mo>
      <mrow>
        <mi>n</mi>
        <mo>=</mo>
        <mn>0</mn>
      </mrow>
      <mrow>
        <mi>s</mi>
        <mo>&#x2212;</mo>
        <mn>1</mn>
      </mrow>
    </munderover>
    <mrow>
      <mi>i</mi>
      <msub>
        <mi>n</mi>
        <mi>n</mi>
      </msub>
      <mo>&#x22c5;</mo>
      <mi>cos</mi>
      <mo>(</mo>
      <mrow>
        <mfrac>
          <mrow>
            <mi>&#x3c0;</mi>
            <mi>k</mi>
          </mrow>
          <mi>s</mi>
        </mfrac>
        <mo>(</mo>
        <mrow>
          <mi>n</mi>
          <mo>+</mo>
          <mfrac>
            <mn>1</mn>
            <mn>2</mn>
          </mfrac>
        </mrow>
        <mo>)</mo>
        </mrow>
      <mo>)</mo>
    </mrow>
  </mstyle>
</math>
```

This renders correctly:
<img width="741" alt="Screenshot 2023-04-27 at 1 51 14 PM" src="https://user-images.githubusercontent.com/11865/234771203-1a3114d3-69e7-46e8-9f87-4820a5307894.png">

**Comment by ronaldtse** [comment]
And we also need to support the `\left(` and `\right)` parentheses input syntaxes.

**Comment by jonsneyers** [comment]
For now, I circumvented the acute problem by just copy/pasting the old rendered formula from the CD .doc version of the document into the DIS .doc version as this is a formula that hasn't changed at all, in fact you'll recognize it as the definition of the DCT which is still the same as the one in the original 1992 JPEG standard :)

So there is no urgency anymore as far as I'm concerned. Of course it would still be nice to iron out these LaTeX parsing issues since I imagine others could be affected by it too.

**Comment by ronaldtse** [comment]
Thanks @jonsneyers for the update and again apologies for this particular issue. FYI for DIS submission you have 2 choices: you could submit the generated Word version, and/or the STS XML version. The copy paste works for the Word version but not sure what will happen in the STS XML in this case (we don’t know how ISO’s code renders MathML).

**Comment by ronaldtse** [comment]
Ping @suleman-uzair for a fix today. Thanks.

**Comment by ronaldtse** [comment]
@suleman-uzair I have installed 0.3.1 which is just released.

However, this problem is not solved?

The generated output in MathML does not seem to use sufficient `mrow` elements within the `<mo>(</mo>` and `<mo>)</mo>` pair:

```xml
    <mrow>
      <mi>i</mi>
      <msub>
        <mi>n</mi>
        <mi>n</mi>
      </msub>
      <mo>&#x22C5;</mo>
      <mrow>
        <mi>cos</mi>
        <mo>(</mo>
      </mrow>
      <mfrac>
        <mrow>
          <mi>&#x3C0;</mi>
          <mi>k</mi>
        </mrow>
        <mi>s</mi>
      </mfrac>
      <mo>(</mo>
      <mi>n</mi>
      <mo>+</mo>
      <mfrac>
        <mn>1</mn>
        <mn>2</mn>
      </mfrac>
      <mo>)</mo>
      <mo>)</mo>
    </mrow>
```

Look at what happens after `cos`. Technically everything after "cos" should go into the `(...)`, but right now the structure is broken.

The MathML rendering now is clearly not using balanced parentheses.

<img width="684" alt="Screenshot 2023-05-10 at 1 07 17 AM" src="https://github.com/plurimath/plurimath/assets/11865/a1a4d9da-38e8-48ec-b773-b7a532bc8cbe">

**Comment by ronaldtse** [comment]
Confirm that the latest #153 worked:

![](https://user-images.githubusercontent.com/11865/237623826-77e7df41-744a-4714-b5bd-95dfc6071406.png)

Thanks!
