### ISSUE TITLE
Struggling to encode a couple of matrix equations

### ISSUE THREAD

**Issue by manuelfuenmayor** [plurimath/plurimath#157]
*Issue found in https://github.com/metanorma/mn-samples-jcgm/pull/29*

I'm struggling to get the proper rendering of these following equations in Metanorma:

1.
![equation-1](https://github.com/metanorma/mn-samples-jcgm/assets/33627611/63f58dd1-bb20-43b2-89da-f3735185d317)

2.
![equation-2](https://github.com/metanorma/mn-samples-jcgm/assets/33627611/9d422975-eb0e-497d-88a6-bcb32bb22ec6)

For the first one I did:

```adoc
bb(C_X)^{(1)} =
[(1 + A theta_1 + B theta_1^2, R_0 theta_1,R_0 theta_1^2,-r_1),
(vdots,vdots,vdots,vdots),
(1 + A theta_{10} + B theta_{10}^2, R_0 theta_{10}, R_0 theta_{10}^2, -r_{10})]
````

and for the second:

```adoc
[(cos{:y_2:},sin y_2),(-(sin y_2)//y_1,(cos y_2)//y_1)] .
````

Both of these encodings show correctly in classic AsciiMath but not in Metanorma:

1. 
![eq1-generated](https://github.com/plurimath/plurimath/assets/33627611/1da7e6ce-3059-4f6a-84ac-d1ca598f0de0)

2. 
![eq2-generated](https://github.com/plurimath/plurimath/assets/33627611/fc82dc40-b226-498d-b5d2-0faf6d53d793)

The document where these equations were found (https://github.com/metanorma/mn-samples-jcgm/pull/29) has dozens of
matrix equations, and these two were the only ones that didn't render properly.

**Comment by ronaldtse** [comment]
Maybe we need to have an easy way for users to verify the equation rendering output…

**Comment by ronaldtse** [comment]
@suleman-uzair can you please help address this? Thanks.

**Comment by ronaldtse** [comment]
@manuelfuenmayor can you help confirm that these equations are now showable in Plurimath? Thanks.

**Comment by manuelfuenmayor** [comment]
@ronaldtse, I'm still getting an incorrect result, as shown in the description.
I'm building with plurimath 0.3.2. Is that the latest update?

**Comment by suleman-uzair** [comment]
> @ronaldtse, I'm still getting an incorrect result, as shown in the description. I'm building with plurimath 0.3.2. Is that the latest update?

@manuelfuenmayor @ronaldtse I apologize for the mistake, The latest version was not released. Could you please verify with the latest version 0.3.3? I just released it.

**Comment by manuelfuenmayor** [comment]
It is perfect now. Thanks @suleman-uzair!
