### ISSUE TITLE
Matrix equation not rendering as expected

### ISSUE THREAD

**Issue by manuelfuenmayor** [plurimath/plurimath#160]
*Issue found in https://github.com/metanorma/pdfa-iso-32000-2/pull/2*

This equation:
````
T_m = T_{lm} = [(a,b,0),(c,d,0),(e,f,1)]
````

renders:
![eq-issue-generated](https://github.com/plurimath/plurimath/assets/33627611/83cc344b-4eb6-4a1c-ba22-2d5df1a0d098)

Expected result:
![eq-issue-original](https://github.com/plurimath/plurimath/assets/33627611/bee72de7-c10a-4599-9df7-cd56e6b78af4)

**Comment by manuelfuenmayor** [comment]
Also there is this case:
````
<< C_{s_i}, f_{j_i}, alpha_{j_i} >> =
{ ("Composite"(C_{i-1},alpha_{i-1},E_i),"if " E_i " is a group"),
("intrinsic color, shape, and "("shape" xx "opacity") " of " E_i, "otherwise") :}
````

that renders:
![eq2-generated](https://github.com/plurimath/plurimath/assets/33627611/386913ea-0c2e-44b6-9220-4000ea02560d)

Expected:
![eq2-expected](https://github.com/plurimath/plurimath/assets/33627611/15286fed-e5d5-465f-8e1b-3ffa7078d3f5)

**Comment by manuelfuenmayor** [comment]
And this one:
````
<< C_g, f_g, alpha_g >> = "Composite"(U,0,P)
````

renders:
![eq3-generated](https://github.com/plurimath/plurimath/assets/33627611/74b01e03-6787-40cc-ace9-e7e33e35abcc)

Expected:
![eq3-expected](https://github.com/plurimath/plurimath/assets/33627611/43be5144-e54c-4680-8ed3-9bdb88fca5c7)

**Comment by ronaldtse** [comment]
@manuelfuenmayor can you please help verify? Thanks!

**Comment by suleman-uzair** [comment]
[manuelfuenmayor](https://github.com/manuelfuenmayor) The changes you mentioned have been implemented in version 0.3.5. Can you please verify?

**Comment by ronaldtse** [comment]
@manuelfuenmayor can you please help verify? Thanks!

**Comment by manuelfuenmayor** [comment]
@suleman-uzair, @ronaldtse, the issue is fixed:
![eq-issue-generated-2](https://github.com/plurimath/plurimath/assets/33627611/cc88d172-eaea-40ba-a88d-cc611c530d49)

Thank you!

**Comment by ronaldtse** [comment]
Thank you guys!
