### ISSUE TITLE
Math expressions involving summation symbol show flaws in presentation

### ISSUE THREAD

**Issue by manuelfuenmayor** [plurimath/plurimath#165]
*Transferred from https://github.com/metanorma/metanorma-standoc/issues/796*
*In relation to https://github.com/metanorma/pdfa-iso-32000-2/issues/5*

Markup sample:
```adoc
S(u,v) = sum_{i=0}^3 sum_{j=0}^3 p_{ij} xx B_i(u) xx B_j (v)
````

DOC output:
![issue15-generated-doc](https://github.com/metanorma/metanorma-standoc/assets/33627611/e0967156-62e3-43f4-bd8d-97ea370e835d)

Original:
![issue15-original](https://github.com/metanorma/metanorma-standoc/assets/33627611/798eee8e-edb2-4dad-946c-53cb3104e5e8)

**Comment by suleman-uzair** [comment]
In **AsciiMath** and other **Markup languages**, we have two parameters(`base` and `power`) for '**sum**', '**prod**', and '**int**', but in **OMML** and **Math zone** presentation we need three parameters.
For instance in '**int**' we have `upper limit`, `lower limit`, and `integral`.

As part of this update, I'll be making changes to the parsing and transformation rules, conversion methods, and specs. This will ensure consistency and compatibility across different representations.

**Comment by opoudjis** [comment]
There is a related issue, unearthed in https://github.com/metanorma/metanorma-standoc/issues/763

The AsciiMath operands `sum prod ^^^ vvv nnn uuu` are being converted to MathML with msub, msup, msubsup. This is wrong: they must be rendered with munder, mover, munderover. It is true that in compact style, the underscript and overscript are rendered as subscript and superscript; but that behaviour is determined through the value of the `displaystyle` attribute, and that only works on munder, mover, munderover. Using msub, msup, msubsup is guaranteeing that all Asciimath limit expressions are only ever rendered in compact style.
