### ISSUE TITLE
Support Unitsml syntax

### ISSUE THREAD

**Issue by suleman-uzair** [plurimath/plurimath#171]
> @suleman-uzair yes let's close this. Instead we can enhance the plurimath gem to support unitsml syntax by delegating to the unitsml-ruby gem.

_Originally posted by @ronaldtse in https://github.com/plurimath/plurimath/issues/112#issuecomment-1651353833_

**Comment by suleman-uzair** [comment]
@ronaldtse , @opoudjis 

Since Unitsml is used for encoding scientific units of measure and quantities and is not a complete markup language for math, I have some questions related to **Unitsml** input and output.
1. Are we expecting the input to always be in the format `"unitsml(\<unitsml-string\>)"` in all languages?
2. Do we need to add a method in the formula to convert it to **Unitsml**?
  a. If yes, what should we do if someone tries to convert a formula from **AsciiMath** to **Unitsml**, for the example “sum_b \“unitsml(mm)\” prod_e”?
3. Are we expecting the output in the same format `"unitsml(\<unitsml-string\>)"`?
  a. If not, then the parsing of output will yield different results because of the missing `unitsml` tag in the output.

**Comment by opoudjis** [comment]
Have debriefed Suleman. In my opinion, we don't need mapping to unitsml, only from.
