### ISSUE TITLE
URGENT: concatenated expressions are now crashing Plurimath

### ISSUE THREAD

**Issue by opoudjis** [plurimath/plurimath#175]
It could well be that these expressions should never have been allowed in Plurimath; but they used to work, and they are now crashing as of this past week, impacting our sample repositories.

Asciimath

````
bar(x) = 1/n sum_{i=1}^n x_i
````

works. But the following, in mn-samples-JCGM, crashes:

````
bar(x) = 1/n sum_{i=1}^n x_i, " " s^2 = 1/{n - 1} sum_{i=1}^n (x_i - bar(x))^2,
````

The crash is:

Maths: Malformed MathML: undefined method `to_mathml_without_math_tag' for {:ternary=>.{...}:Hash}

**Comment by opoudjis** [comment]
Same issue in mn-samples-BIPM:

Plurimath::Math.parse('ii(M)_(12) = 11 - sum_(j=2)^(10) 2^j ((12),(j)) ii(B)_j = ... = -2" "073', :asciim
ath).to_mathml

crashes

Btw, I am dismayed to see `-2" "073` encoded as a number. If that is causing crashes, I am happy to order it not to be.

**Comment by ronaldtse** [comment]
@suleman-uzair there should never be a "method not found" crash. Please help fix error handling as part of this task. Thanks.

@opoudjis `-2" "073` for sure is not a number... any bad things that happen due to that is fair game I guess.

**Comment by opoudjis** [comment]
> @opoudjis `-2" "073` for sure is not a number... any bad things that happen due to that is fair game I guess.

I agree on that, and have already made a pronouncement in the Skype editors channel: I will take care of the spaces in Presentation XML postprocessing of MathML. OTOH, expressions separated with commas are mathematically not a single expression, but are legitimate in our documents...

**Comment by suleman-uzair** [comment]
> @suleman-uzair there should never be a "method not found" crash. Please help fix error handling as part of this task. Thanks.
> 

@ronaldtse Agreed, I’m working on fixing the error handling as part of this task. I’ll update the opened PR#176 with this fix.
