### ISSUE TITLE
Never ever use HTML escapes in plurimath

### ISSUE THREAD

**Issue by opoudjis** [plurimath/plurimath#183]
`&nsbp;` is understood fine in HTML. But Metanorma is not HTML, it is XML. And in XML, escapes like that are not understood at all without special processing. 

Please replace all named escapes in Plurimath output (other than `&gt; &lt; &amp;`) with hexadecimal escapes; e.g. `&#xa0;` not `&nbsp;`

**Comment by ronaldtse** [comment]
I think when @opoudjis says "But Metanorma is not HTML, it is XML" he means "MathML/OMML is not HTML, it is XML".

@opoudjis can you provide an example of what formula you're seeing this behavior? That'd be helpful. Thanks!

**Comment by suleman-uzair** [comment]
> I think when @opoudjis says "But Metanorma is not HTML, it is XML" he means "MathML/OMML is not HTML, it is XML".
> 
> @opoudjis can you provide an example of what formula you're seeing this behavior? That'd be helpful. Thanks!

@ronaldtse Got it, Thanks for the explanation. I will fix this in #182.

**Comment by opoudjis** [comment]
Well, more to the point, I am processing the received OMML using XML tools, not HTML tools. But it is safer to use hex anyway.

The example is the test case:

````
u = <<~HERE
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <mstyle displaystyle="true">
    <mrow>
      <mi>H</mi>
      <mtext>&#xa0;original&#xa0;</mtext>
      <mi>J</mi>
    </mrow>
  </mstyle>
</math>
HERE

Plurimath::Math.parse(u, :mathml).to_omml

The result is:

````
<m:oMath>
    <m:r>
      <m:t>H</m:t>
    </m:r>
    <m:r>
      <m:t>&nbsp;original&nbsp;</m:t>
    </m:r>
    <m:r>
      <m:t>J</m:t>
    </m:r>
  </m:oMath>
````

But I pass that to Nokogiri::XML to manipulate, and Nokogiri::XML only understands XML escapes, not HTML escapes. And yes, I can add a preface to define HTML escapes so that Nokogiri understands the output, but I shouldn't need to...
````

**Comment by ronaldtse** [comment]
Related to https://github.com/plurimath/plurimath/issues/184

**Comment by opoudjis** [comment]
No, this is not fixed in the latest release. I am still getting `&nbsp;`, not `&#xa0;`.

I'm seeing the code snippet:

````
if lang == "omml"
            entities = HTMLEntities.new
            entities.encode(
              entities.decode(parameter_one.gsub(/ /, "&nbsp;")),
              entities.decode(parameter_one&.gsub(/ /, "&#xa0;")),
              :named,
            )
````

(a) You don't want to restrict decoding to just nbsp
(b) :named is precisely what I *don't* want, I need :hexadecimal there.
