### ISSUE TITLE
Crash in JCGM GUM 6:2020 document

### ISSUE THREAD

**Issue by ronaldtse** [plurimath/plurimath#195]
Crash in https://github.com/metanorma/mn-samples-jcgm/issues/35

The crashes are on these formulas:

```
---- FORMULA BEGIN ----
x//
---- FORMULA END ----

---- FORMULA BEGIN ----
u(x)//
---- FORMULA END ----

---- FORMULA BEGIN ----
(u(x)//x)//
---- FORMULA END ----

---- FORMULA BEGIN ----
(u(r)//r)//
---- FORMULA END ----

---- FORMULA BEGIN ----
x = ((I_x + varepsilon_x))/I_"ref" x_"ref"
---- FORMULA END ----
```

Tracked at https://github.com/metanorma/mn-samples-jcgm/issues/35

**Comment by opoudjis** [comment]
Sorry to say this, but the source document is gibberish:

````
stem:[x//] +
stem:[("unitsml(nmol/mol)")]
````

is semantically nonsense, and making Suleman parse it as if it is meaningful is completely counterproductive. What is actually intended here is:

````
stem:[("x// \ unitsml(nmol/mol)")]
````

That is, a line break is what is intended here, as we have recently implemented (and are still trying to render), and it should not be compromising the source semantics. A source semantics that you have always wanted preserved in Metanorma, @ronaldtse . The Math expression should be broken  up into presentation bits as part of rendering, as we are doing now with line break, and not as part of the input semantics.

Suleman can introduce code to deal with fractions with missing denominators, but fractions with missing denominators are not meaningful, and nothing is going to communicate in that example that `stem:[("x// \ unitsml(nmol/mol)")]` is a numerator.

**Comment by suleman-uzair** [comment]
@ronaldtse PR[#197](https://github.com/plurimath/plurimath/pull/197) is now available for review. Let me know your thoughts on merging.

@opoudjis, According to the current implementation the new line in **AsciiMath** is represented by a `backslash followed by a newline character(\n)` as mentioned [here](https://github.com/plurimath/plurimath/issues/179#issuecomment-1723289794), so the example

> stem:[("x// \ unitsml(nmol/mol)")]

 will become something like:

> stem:[("x// \\n unitsml(nmol/mol)")]

or

> stem:[("x// \ \n unitsml(nmol/mol)")]
