### ISSUE TITLE
Symbol/String distinction inside lib/plurimath/math/symbol.rb

### ISSUE THREAD

**Issue by hmdne** [plurimath/plurimath#198]
I am dealing with this testcase: `rspec ./spec/plurimath/omml_spec.rb:60 # Plurimath::Omml.to_latex, to_mathml, to_asciimath contains example #01 returns parsed Asciimath to Formula` - in particular with MathML output.

The diff I receive, where `-` is correct, `+` is what my (Opal) port outputs.

```diff
        <math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
          <mstyle displaystyle="true">
            <msubsup>
       -      <mo>&#x222b;</mo>
       +      <mo>int</mo>
              <mn>2</mn>
              <mn>1</mn>
            </msubsup>
```

I have tried to investigate this problem thoroughly. What I found is this. The difference stems from this particular function:

https://github.com/plurimath/plurimath/blob/main/lib/plurimath/math/symbol.rb#L28-L40

In particular, this fragment:

```ruby
          mo_value = (unicodes[value] || unicode || value).to_s
```

In the case of Opal, `unicodes[value]` is truthy, so the final result is `int`. In case of Ruby, this is falsy, so the final result is `&#x222b;`.

 value is `"&#x222b;"`. Let's find this Hash.

https://github.com/plurimath/plurimath/blob/main/lib/plurimath/mathml/constants.rb#L96

Ok - so it's quite simple why this is falsy in Ruby. `"&#x222b;": "int",` is equivalent to `        :"&#x222b;" => "int",`. Symbols are not Strings, there's only Symbol available, there's no String with such a name in this hash, so we get to return `value` which is `"&#x222b;"` and test passes.

In Opal, Strings are the same type as Symbols. So, incorrectly, this is truthy and the value of the entire expression is `"int"`, so the test fails.

I have re-ran the test suite using Ruby (not Opal) and it seems like, `value` is always a `String`, never a `Symbol` (for all test cases at least). Therefore if I just patch the file `lib/plurimath/math/symbol.rb` this way...:

```diff
diff --git a/lib/plurimath/math/symbol.rb b/lib/plurimath/math/symbol.rb
index 70f8b37..7f81670 100644
--- a/lib/plurimath/math/symbol.rb
+++ b/lib/plurimath/math/symbol.rb
@@ -32,7 +32,7 @@ module Plurimath
         unicodes = Mathml::Constants::UNICODE_SYMBOLS
         unicode = unicodes.invert[value]
         if operator?(unicode) || unicode || explicit_checks(unicode)
-          mo_value = (unicodes[value] || unicode || value).to_s
+          mo_value = (unicode || value).to_s
           return Utility.ox_element("mo") << mo_value
         end
 ```

...the Ruby-side stays equivalent and at the same time Opal passes the test.

I have a suspicion though, that this isn't what was intended. In fact, I suppose that the logic in this function may be incorrect, and what was supposed to happen was this..., at least (if not even the `unicode` variable should work in a different way):

```diff
diff --git a/lib/plurimath/math/symbol.rb b/lib/plurimath/math/symbol.rb
index 70f8b37..7f81670 100644
--- a/lib/plurimath/math/symbol.rb
+++ b/lib/plurimath/math/symbol.rb
@@ -32,7 +32,7 @@ module Plurimath
         unicodes = Mathml::Constants::UNICODE_SYMBOLS
         unicode = unicodes.invert[value]
         if operator?(unicode) || unicode || explicit_checks(unicode)
-          mo_value = (unicodes[value] || unicode || value).to_s
+          mo_value = (unicodes[value.to_sym] || unicode || value).to_s
           return Utility.ox_element("mo") << mo_value
         end
 ```

...but then the tests are also incorrect. Can you perhaps take a second look at this logic?

_Originally posted by @hmdne in https://github.com/plurimath/plurimath/issues/196#issuecomment-1803848178_

**Comment by suleman-uzair** [comment]
@hmdne Thank you for pointing this out I’ve updated the code and opened PR #199 for this.
