### ISSUE TITLE
Implement Plurimath gem that bridges the latexmath and asciimath gems

### ISSUE THREAD

**Issue by ronaldtse** [plurimath/plurimath#2]
The Plurimath gem is supposed to provide a central interface for conversion of multiple math representation languages, including:

* MathML presentation
* MathML semantical
* Microsoft Office Math Markup Language ([omml2mathml](https://github.com/plurimath/omml2mathml))
* AsciiMath ([mathml2asciimath](https://github.com/plurimath/mathml2asciimath))
* LaTeX math ([latexmath](https://github.com/plurimath/latexmath))
* HTML math ([html2asciimath](https://github.com/plurimath/html2asciimath))

Right now we have individual gems that handle 1-to-1 conversions, but we want to combine it all using a single math representation model.

That model may likely be MathML 3.0.

It should also handle UnitsML syntax.

cc: @hassanakbar

**Comment by ronaldtse** [comment]
We need an interface like:

```ruby
am = Plurimath.parse("some ascii math", type: asciimath)
=> Asciimath parsed tree

am.to_mathml
=> <MathML ...>

lm = Plurimath.parse("some latex math", type: latex)
=> Latexmath parsed tree object

lm.to_mathml
=> <MathML ...>
```

**Comment by ronaldtse** [comment]
@suleman-uzair please help handle this. Thanks!

**Comment by suleman-uzair** [comment]
> @suleman-uzair please help handle this. Thanks!

@ronaldtse I am working on it.

**Comment by ronaldtse** [comment]
@suleman-uzair is this completed?

**Comment by suleman-uzair** [comment]
This is the main ticket for tracking all the conversions, currently, **MathML** and **ASCII-Math** conversions are complete and I’m currently working on **Latex** conversion (parsing & transformation rules and **``` Formula ```** to **Latex** reverse conversion).
The remaining conversions are **HTML Units-ml Unicode** and **OM-ML**.

**Comment by ronaldtse** [comment]
Since Asciimath <=> LaTeX math <=> MathML implementation is complete, let's close this issue and track the rest with new ones. Thanks!

**Comment by ronaldtse** [comment]
Closing in favour of individual issues:
* #27 
* #28
* #29
* #30 
* #31 
* #32 
* #33
