### ISSUE TITLE
`\emptyset` cannot be generated in Latex mode

### ISSUE THREAD

**Issue by anermina** [plurimath/plurimath#213]
Plurimath cannot generate `\emptyset` in Latex mode.

![image](https://github.com/plurimath/plurimath/assets/55683568/fc761d61-78e8-46f4-887e-69890e644459)

Using `\varnothing` could be an alternative, but I believe `\emptyset` is not deprecated and should be producible.

**Comment by ronaldtse** [comment]
@suleman-uzair can you help investigate? We probably need to support this math concept. Thanks.
