### ISSUE TITLE
Implement MathML `intent` attribute

### ISSUE THREAD

**Issue by ronaldtse** [plurimath/plurimath#219]
UnicodeMathML implements `intent` as follows:
* https://github.com/MurrayIII/UnicodeMathML#mathml-intent-attribute-support

> - The derivative and partial-derivative intent attributes are defined for Leipzig and Euler derivative notations.
> - The templates […,…], […,…[, ]…,…], and ]…,…[, produce closed-interval, closed-open-interval, open-closed-interval, and open-interval structures, respectively, each including the intent attribute with the interval name and arguments. The … can be a signed number, variable name or ∞. Similarly, the templates (…,…], and […,…) also produce open-closed-interval and closed-open-interval structures with the corresponding intent attribute values. The template (…,…) isn't given an intent attribute since it can be used for a math-function argument list or a point in a 2D plane.
> - The \intent (ⓘ) and \arg (ⓐ) options are defined for enclosures, factorials, fences, atoms, sub/superscripts, and other expressions, thereby enabling the user to add intents explicitly to these constructs.
> - \abs for unambiguous entry of absolute value with the absolute-value intent attribute. \choose along with its intent attribute (binomial-coefficient). Intent attributes are included for UnicodeMath equation arrays, matrices, and determinants.
> - Default intents are defined for \abs, \choose, \cases, fences, n-ary objects, math-function objects, transpose objects, and double-struck italic symbols like differential d (ⅆ). This improves MathML readablity and supports round-tripping these concepts via MathML.

The usage of `intent` is described in MathML 4:
* https://www.w3.org/TR/mathml4/#mixing

The "intent concept dictionary" is at:
* https://docs.google.com/spreadsheets/d/1EsWou1K5nxBdLPvQapdoA9h-s8lg_qjn8fJH64g9izQ

**Comment by suleman-uzair** [comment]
@ronaldtse 
Sure. Will work on it after other ongoing tasks.

**Comment by suleman-uzair** [comment]
Do we need to only support the parsing of intent attribute or do we also need to calculate it based on the input and the “intent concept dictionary” provided above? i.e do we need to calculate intent for AsciiMath equation `lim▒_(n→∞) a_n` to **MathML** conversion(as mentioned in **UnicodeMathML** examples)
```
<math display=“inline”>
  <mrow intent=“:function”>
    <msub>
      <mi>lim</mi>
      <mrow>
        <mi>𝑛</mi>
        <mo stretchy=“true”>→</mo>
        <mi>∞</mi>
      </mrow>
    </msub>
    <mo>⁡</mo>
    <msub>
      <mi>𝑎</mi>
      <mi>𝑛</mi>
    </msub>
  </mrow>
</math>
```

**Comment by ronaldtse** [comment]
@suleman-uzair yes, when we support intent, we should support the encoding of them in MathML. We should have two output modes in MathML, to include intent or not.
