### ISSUE TITLE
Add spaces before UnitsML in MathML conversion(using Oga)

### ISSUE THREAD

**Issue by suleman-uzair** [plurimath/plurimath#223]
Add spaces before **Unitsml** in **MathML** output following the instructions mentioned in the https://github.com/metanorma/bipm-si-brochure/issues/222

Process **Oga** nodes in post conversion methods.

**Comment by ronaldtse** [comment]
@suleman-uzair I wonder if we should abstract out the XML adapter? So we are not bound by implementation specific code in the core.
