### ISSUE TITLE
Create number formatter in Plurimath

### ISSUE THREAD

**Issue by opoudjis** [plurimath/plurimath#232]
In https://github.com/metanorma/iso-iec-80000/issues/39 the desire was expressed to move number formatting code from Metanorma to Plurimath. The code is 

https://github.com/metanorma/isodoc/blob/main/lib/isodoc/presentation_function/math.rb : localized_number(), and probably twitter_cldr_localiser() (which draws on [twitter-cldr-rb](https://github.com/twitter/twitter-cldr-rb) for its definition of number localisation, and expands on it).

Note that flavours customise twitter_cldr_localiser_symbols(), to define default rendering for the Metanorma flavour, overriding the values given by twitter-cldr-rb for the current locale. For example,

https://github.com/metanorma/isodoc/blob/2d650f7788abf0eb14d89858c7877c3e36f927d3/lib/isodoc/presentation_function/math.rb#L65

````
def twitter_cldr_localiser_symbols
        { group: "'" }
end
````

That tells ITU to break up groups of three digits with "'" not space.

https://github.com/metanorma/metanorma-bipm/blob/4aab355394d6a6b18ff884100627f3d102548ffb/lib/isodoc/bipm/presentation_xml_convert.rb#L77

````
      def twitter_cldr_localiser_symbols
        { group: "&#xA0;", fraction_group: "&#xA0;",
          fraction_group_digits: 3 }
      end
````

That tells BIPM to separate digits and fraction digits, every 3 digits, with nbsp. I want to pass the hash in twitter_cldr_localiser_symbols to the class realising this number formatter, since they are defaults for the entire run.

I am requesting that you integrate this code into Plurimath, so long as I can call it cleanly: it will be a different class of code than the Plurimath code conversions, and it will take a numeric string as input, not a MathML node. Note that localize_maths() in that code is actually iterating through mn, and calculating what the precision of the number is if it isn't given. You may end up doing that in general for all rendered MathML, but don't do it yet. 

I'm only going to give you a numeric string, and ask you to calculate the precision if it is not given. I also want you to generate the parameters which are being assumed in my code, locale, twitter_cldr_reader, and twitter_cldr_localiser_symbols.

I am THEN asking you to expand this method to do scientific notation. But one thing at a time.

This is how I am currently invoking localized_number(). Note that precision is derived if not given; and that twitter_cldr_reader has already been initialised from locale before running this code.

````
def localize_maths(node, locale)
      node.xpath(".//m:mn", MATHML).each do |x|
        num = BigDecimal(x.text)
        precision = /\./.match?(x.text) ? x.text.sub(/^.*\./, "").size : 0
        x.children = localized_number(num, locale, precision)
      rescue ArgumentError
      end
    end
````

I want you to realise the following code, integrating my code:

````
require "twitter-cldr-rb"

class Plurimath::Numberformatter
def initialize(locale_str: "en", twitter_cldr_localiser_symbols: {})
  @locale,  @twitter_cldr_reader = twitter_cldr_localiser(locale_str)
  @twitter_cldr_localiser_symbols = twitter_cldr_localiser_symbols
end

    def twitter_cldr_reader(locale)
      return @twitter_cldr_reader if @twitter_cldr_reader

      num = TwitterCldr::DataReaders::NumberDataReader.new(locale)
      num.symbols.merge!(@twitter_cldr_localiser_symbols)
        .merge!(parse_localize_number)
    end

    def twitter_cldr_localiser(locale_str: "en")
      locale = TwitterCldr.supported_locale?(locale_str.to_sym) ? locale_str.to_sym : :en
      [locale , twitter_cldr_reader(locale)]
    end

  def parse_localize_number
  # taken from my code: these are the default values of the various parameters determining how the number formatter behaves
 end

# note: I have not defined digitcount yet
def localized_number(number_string, locale: "en", precision: nil, digitcount: nil, format: {})
   locale_sym, reader = if locale == @locale.to_s
     [@locale,  @twitter_cldr_reader]
   else
     twitter_cldr_reader(locale)
   end
   num = BigDecimal(number_string.to_s) # we need arbitrary precision
   precision ||= /\./.match?(x.text) ? x.text.sub(/^.*\./, "").size : 0 # if we don't know the precision, infer it
   reader.merge!(format)
   localized_number(num, locale_sym, reader, precision) # from this point use my existing implementation, but with twitter_cldr_reader now an explicit parameter, in case we switch it mid-run
end

end
````

As a result, I expect to be able to make the following calls 

````
n = Plurimath::Numberformatter.new("de", { group: "&#xA0;", fraction_group: "&#xA0;",
          fraction_group_digits: 3 }) 
n.localized_number(1) # 1
n.localized_number("1") # 1
n.localized_number(1.6, locale: "en") # 1.6
n.localized_number(1.6, locale: "fr", precision: 3) # 1,600 : the locale "fr" is resulting in twitter_cldr_reader reading in French localisation of numbers, according to which the parameter "decimal", delimiting decimal numbers, is "," not "."
n.localized_number(1.6, locale: "fr", precision: 3, format: {decimal: "*"} ) # 1*600 : override the locale parameter "decimal" with my own
````

**Comment by opoudjis** [comment]
Continuing:

The format hash, which appears in localized_number(format: {}) and in twitter_cldr_localiser_symbols(), has the following values taken from twitter-cldr-rb, and which I inherit the implementation of from twitter-cldr-rb:

* group_digits: the number of digits to group integers by; default is 3; e.g. 1,000,000
* group: the character to delimit groups of integers by; if space, you get 1 000 000, if "'", you get 1'000'000
* decimal: the character to separate integers from decimals by; "." in English, "," in French (and ISO English)

The following values have been added and implemented by me:

* fraction_group_digits: the number of digits to group decimals by; default is 3; e.g. 0.000 001
* fraction_group: the character to delimit groups of decimals by; if space, you get 0.000 001, if "'", you get 0.000'001



{ 
              fraction_group_digits: m[:fractdigits].size,
              group: m[:group] || "",
              fraction_group: m[:fractgroup] || "" }.compact

**Comment by opoudjis** [comment]
Now, once you've implemented all of that, I want you to enhance functionality of this number formatter beyond what I've already implemented, to support scientific notation. This will involve the following additional parameters to format{} (although I've put digitcount as a separate parameter; you can of course work out the arrangement of parameters that makes sense to you.) 

* digitcount: precision counts the number of allowed digits after the decimal point (or comma). digitcount counts the number of allowed significant digits in the whole number. So n.localized_number(10.6, locale_str: "fr", precision: 4) = "10.6000", but n.localized_number(10.6, locale_str: "fr", digitcount: 4) = "10.60", and n.localized_number(10.6, locale_str: "fr", digitcount: 2) = "11"
* notation: has the following possible values:
  * basic (default): what we are used to, e.g. 14000
  * scientific: 1.4 × 10<sup>4</sup>
  * engineering: 14 × 10<sup>3</sup> : the exponent must be rounded down to a multiple of 3
  * e: 1.4e4
* times: the symbol to use for multiplication in scientific/engineering notation, can be × or · or * or whatever user provides
* exponent_sign: if this is specified as "plus", then positive exponents in scientific/engineering/e must have a plus sign added, e.g. 1.4 × 10<sup>+4</sup>, 1.4e+4
* e: the exponent symbol in E notation, can be "e" or "E" (Wikipedia gives more obscure alternatives in https://en.wikipedia.org/wiki/Scientific_notation ). In ISO 2533, which is why we are doing this, the scientific notation looks like 1.4442 +7, which ends up being notation: "e", e: "&#xa0;", exponent_sign: "plus".

**Comment by opoudjis** [comment]
This is breaking my tests on isodoc, and I have not had the time to integrate the new formatter.

I am not happy about this, @suleman-uzair . 

The particular discrepancies are as follows:

1. Default French customisation in isodoc, spec/isodoc/presentation_xml_maths_spec.rb  line 254 is now inserting spaces in decimals: 0,0000032 is now 0,000 003 2. The thing is, that behaviour is not undesirable as such, but it is also not something I had anticipated as a default. Are you defaulting in assuming that fraction_group_digits = group_digits? If so, we need to document that behaviour.

2. The test in spec/isodoc/presentation_xml_maths_spec.rb line 186 is yielding wrong-looking behaviour. I am passing in 

````
    let(:additional_symbols) do
      {
        fraction_group_digits: 2,
        fraction_group: "'",
        precision: 5,
      }
    end

    before do
      allow_any_instance_of(IsoDoc::PresentationXMLConvert)
        .to(receive(:twitter_cldr_localiser_symbols)
        .and_return(additional_symbols))
    end
````

With that custom set of config, I expect in the test the number `459384.123456789` to render as `459,384.12'34'56` : group fractional digits by twos, delimit them by ', and 5 decimal digits.

I am now getting `459,384.12''3'4'`. That suggests to me that the implementation is buggy; please investigate.

3. The `localizenumber` setting of number format templates is no longer working, although I was proposing to get rid of it as too hard to maintain anyway, but please investigate what has happened. In spec/isodoc/presentation_xml_maths_spec.rb line 301 I am passing `localizenumber: "#=#0;##$#"` and the numbers 64212149677264515 and 642121496772.64515. I expect to get `64=212=149=677=264=515` and `642=121=496=772;64$51$5`. I am getting `6=42=12=14=96=77=26=45=15` and `64=21=21=49=67=72;64$$5$1$`. The duplicate symbol for decimal digit groups and dropping digits is the same bug as in 2. 
4. 
5. The grouping of digits by twos instead of threes, on the other hand, does appear to be correct, and my implementation incorrect: #=#0; should be read as #0 => two digits (and I have no idea how I was getting the regex to parse it as threes.)

**Comment by opoudjis** [comment]
I'm ok with this. Three things, which do not need to hold up release:

1. Plurimath::NumberFormatter => Plurimath::Formatter::NumberFormatter is slightly confusing, but makes sense: the former is a shell, generating the necessary parameters to invoke the latter. You're trying to avoid the confusion by naming the latter NumericFormatter, but that's even more confusing in my opinion, because  Plurimath::NumberFormatter and Plurimath::Formatter::NumericFormatter do not actually involve different functionality. But not worth fixing.
2. You are still supporting the localizenumber template (and as I said, I do not currently want to extend it to scientific notation); but you are not testing it anywhere; you set it in spec/plurimath/number_formatter_spec.rb line 62, but you don't do anything with it. I'd like to see a test just of that template.

3. There is an issue raised by the parsing_wrapper, which I'm going to raise as a separate ticket.

Please release.

**Comment by suleman-uzair** [comment]
@opoudjis, Just released version 0.8.4.

**Comment by ronaldtse** [comment]
@suleman-uzair can you please help update document on plurimath.org and the README? Thanks.

**Comment by opoudjis** [comment]
Sorry, bug found when I tried to integrate this into isodoc.

The isodoc implementation of this relies on BigDecimal to preserve arbitrary numbers of digits in the numeric string.

My test case is localising `642121496772645.15`

lib/plurimath/formatter/numeric_formatter.rb is:

````
num = num.match?(/\./) ? num.to_f : num.to_i
localized = localize(BigDecimal(num.to_s))
````

The first line is using Ruby float and integer, which are *not* arbitrary precision numbers. Therefore, by the time we get to the next line, BigDecimal, it is too late: `642121496772645.15` has already been truncated to `642121496772645.1`

I don't do `num = num.match?(/\./) ? num.to_f : num.to_i` in my code, and I don't think you should either.

**Comment by opoudjis** [comment]
I've removed the line and tried to run rspec, but I'm getting

````
An error occurred while loading ./spec/plurimath/unicode_math/plurimath/unicodemath_transform_spec.rb.
Failure/Error: unicodemath_tests_file = File.read("submodules/unicodemath-tests/unicodemath_tests.yaml")

Errno::ENOENT:
  No such file or directory @ rb_sysopen - submodules/unicodemath-tests/unicodemath_tests.yaml
# ./spec/plurimath/unicode_math/plurimath/unicodemath_transform_spec.rb:12:in `read'
# ./spec/plurimath/unicode_math/plurimath/unicodemath_transform_spec.rb:12:in `block (2 levels) in <top (required)>'
# ./spec/plurimath/unicode_math/plurimath/unicodemath_transform_spec.rb:8:in `block in <top (required)>'
# ./spec/plurimath/unicode_math/plurimath/unicodemath_transform_spec.rb:7:in `<top (required)>'
````

Anyway, removing that line fixes my isodoc issues. Please do so and release
