### ISSUE TITLE
Validate MathML output against MathML XSD

### ISSUE THREAD

**Issue by ronaldtse** [plurimath/plurimath#233]
Let's validate our MathML output with the official MathML XSD.

For every formula generated into MathML, we validate it against this XSD in RSpec.

_Originally posted by @suleman-uzair in https://github.com/plurimath/plurimath/issues/231#issuecomment-2031634129_

**Comment by suleman-uzair** [comment]
@ronaldtse, does this still need to be implemented, or can we close this issue since we are processing **MathML** using **Lutaml-Model** generated classes from the **MathML-XSD**?

**Comment by ronaldtse** [comment]
@suleman-uzair there is no need anymore because the `mml` gem already ensures that the output is always valid against the XSD. We should probably have a way of testing the `mml` output against the XSD.
