### ISSUE TITLE
Need significant digits

### ISSUE THREAD

**Issue by opoudjis** [plurimath/plurimath#264]
The number formatter needs to be able to specify the number of significant digits. This is particularly important for Metanorma, as I will be formatting the number by default to the number of significant digits provided, and I am ending up translating in and out of e-notation: https://github.com/metanorma/metanorma-standoc/issues/882

I have been using digit_count to that end until now. But when faced with leading zeroes, digit_count is clearly counting leading zeroes. If this is about fitting digits on a screen, I see that it needs to. But I do need the ability to specify significant digits as distinct from digit count. And (unlike what BigDecimal does) I need trailing zeroes to be considered significant.

So:

````
num1 = "0.001"
puts Plurimath::NumberFormatter.new(:de).localized_number(num1, format: {}) == 0,001
puts Plurimath::NumberFormatter.new(:de).localized_number(num1, format: {:digit_count=>3}) == 0,0 # !!!
puts Plurimath::NumberFormatter.new(:de).localized_number(num1, format: {:digit_count=>3, notation: :scientific}) == 1,0000 × 10^-03
````

(Not sure what is going on with the last one: is it counting the exponent as a significant digit, somehow? The second also looks wrong.)

What I need is:

````
puts Plurimath::NumberFormatter.new(:de).localized_number(num1, format: {:digit_count=>3}) == 0,00 # three digits
puts Plurimath::NumberFormatter.new(:de).localized_number(num1, format: {:digit_count=>6, notation: :scientific}) ==  1,00 × 10^-03 OR 1,00000 × 10^-03 # need to decided whether counting exponent digits or not. I think we do, and I also think we aren't at the moment....
puts Plurimath::NumberFormatter.new(:de).localized_number(num1, format: {:significant=>3}) == 0,00100
puts Plurimath::NumberFormatter.new(:de).localized_number(num1, format: {:significant=>3, notation: :scientific}) == 1,00 × 10^-03
````

So that `100` are the three significant digits. And that  is regardless of how many digits  are actually displayed. (So I expect digit_count to include leading zeroes, and significant not to.)

This applies for fractional digits; for integers, digit_count is acting like I expect significant to.

**Comment by opoudjis** [comment]
Minor note:

Plurimath number formatter gets very confused when I pass it a number in e-notation, as is native out of BigDecimal: it gets things placement of decimals and groups completely wrong when it sees "0.1e-2". 

In order to deal with this, I pass it `BigDecimal(num).to_s("F")`; that is, I force any e-notation input to be floating point notation, which is what it expects to see. That works fine, and is consistent with code assumptions about decimal points; and I have no problem with Plurimath treating all numbers as floating point representation internally. But I think that conversion should be done within Plurimath, the minute it sees the number to format, so that I can pass it e-notation without needing to convert it.

**Comment by opoudjis** [comment]
@suleman-uzair Am going away for a week Saturday; request this be done by 8 July when I'm back.

**Comment by suleman-uzair** [comment]
> this be done by 8 July

@opoudjis I will do my best!

**Comment by opoudjis** [comment]
I've just realised, you are returning exponents in scientific/engineering notation in Ascii superscript, `1,00'00'00'0 × 10^+21`. That's fine, but (a) document it, and (b) I will need to convert that in postprocessing to either `<sup>` (when the number ends up outside of MathML) or `<msup><mn>...</mn><mn>...</mn></msup>` (when it remains within it).
