### ISSUE TITLE
Problem with rendering "log_10"

### ISSUE THREAD

**Issue by ronaldtse** [plurimath/plurimath#265]
This formula:
```
"ISLR"=10log_10 {(P_("total")-P_("main"))/P_("main") }
```

<img width="1086" alt="Screenshot 2024-06-26 at 9 43 45 PM" src="https://github.com/plurimath/plurimath/assets/11865/2a66dd2b-9a87-4fe6-849c-1a3cfc8b27f7">

Notice that the "log_10" is entirely missing in the rendering.

If I remove the `_10` part from `log_10`, then the `log` comes back:

<img width="1081" alt="Screenshot 2024-06-26 at 9 44 23 PM" src="https://github.com/plurimath/plurimath/assets/11865/586fc038-46df-48de-90ac-184e2ad56d3d">

**Comment by opoudjis** [comment]
Overlap with

https://github.com/plurimath/plurimath/issues/210
https://github.com/plurimath/plurimath/issues/228

?

**Comment by suleman-uzair** [comment]
> Overlap with
> 
> #210 #228
> 
> ?

@opoudjis No, this issue will not overlap with other issues.
#210 was about the empty `<mi/>` in the **msubsup** for logarithms triggering the error, and #228 was related to **Word** crashing due to **m:supHide** and **m:subHide** tags in **m:sSubSup**.
