### ISSUE TITLE
Implement parsing of OMML into Formula

### ISSUE THREAD

**Issue by ronaldtse** [plurimath/plurimath#27]
The plurimath gem should re-implement the functionality of parsing Microsoft Office Math Markup Language (OMML) into a Formula:

Please refer to the code in the [omml2mathml gem](https://github.com/plurimath/omml2mathml)

**Comment by ronaldtse** [comment]
@suleman-uzair this is done, right? If so please close it, thanks.

**Comment by suleman-uzair** [comment]
Fixed in #52
