### ISSUE TITLE
Deprecate all math gems that Plurimath supersedes

### ISSUE THREAD

**Issue by ronaldtse** [plurimath/plurimath#307]
* [x] Deprecate plane1converter
* [x] Deprecate latexmath
* [x] Deprecate asciimath2unitsml
* [x] Deprecate omml2mathml
* [x] Deprecate html2asciimath
* [x] Deprecate unicode2latex
* [x] Deprecate mathml2asciimath
* [x] Deprecate latexmath-js (point to plurimath-js)

For each of these repositories, we need to:
* Update the README with a deprecation notice (keep the content, but have the deprecation notice at the top)
* Point the user to use Plurimath instead

**Comment by suleman-uzair** [comment]
@ronaldtse, I have added the deprecation notice, a screenshot of the notice is attached below.
Let me know if any changes are required.

![Screenshot 2024-11-20 at 1 39 31 PM](https://github.com/user-attachments/assets/5edeca58-da23-4620-a1b4-c888e3b976e7)

**Comment by ronaldtse** [comment]
Thanks @suleman-uzair !
