### ISSUE TITLE
Much greater than and much less than symbols

### ISSUE THREAD

**Issue by anermina** [plurimath/plurimath#308]
Is it possible to add the `mgt` (much greater than) and `mlt` (much less than) symbols to render using `stem` notation, to avoid the need for using `latexmath` to generate these symbols properly?

There is a ticket addressing this in asciimath: https://github.com/asciimath/asciimathml/issues/96.

**Comment by ronaldtse** [comment]
@suleman-uzair please help prioritize this. Thanks!
