### ISSUE TITLE
Crash when parsing the equivalent of `2^256` in MathML

### ISSUE THREAD

**Issue by ronaldtse** [plurimath/plurimath#313]
```
[plurimath] Error: Failed to parse the following formula with type `asciimath`.
[plurimath] Please first manually validate the formula.
[plurimath] If this is a bug, please report the formula at our issue tracker at:
[plurimath] https://github.com/plurimath/plurimath/issues
---- FORMULA BEGIN ----
<math xmlns="http://www.w3.org/1998/Math/MathML">    <mstyle displaystyle="false">      <msup>        <mn>2</mn>        <mn>256</mn>      </msup>    </mstyle> </math><asciimath>2^256</asciimath>
---- FORMULA END ----
~/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/plurimath-0.8.17/lib/plurimath/math.rb:70:in `parse_error!'
```

**Comment by ronaldtse** [comment]
I believe this is crashing when the MathML generated by Plurimath is then parsed by Plurimath.

<img width="541" alt="Screenshot 2024-12-09 at 10 37 21 PM" src="https://github.com/user-attachments/assets/14552c93-654c-4076-9b58-8691a6d05bef">

**Comment by suleman-uzair** [comment]
@ronaldtse
1. Error mentions the input as `:asciimath` while the input is `mathml`.
2. The input contains `<asciimath>2^256</asciimath>` at the end which is invalid. I have tested it by removing this part and it’s working fine with **Plurimath** and **Mml**.

I have tested the string (with and without the `<asciimath>` part) using `:mathml` and `:asciimath` languages but the error was never raised.
Could you please provide me with some more details so I can reproduce the error?

**Comment by ronaldtse** [comment]
The error actually originates here:
* https://github.com/metanorma/metanorma-ietf/issues/217

I'm not exactly sure how this happens. Maybe @opoudjis can give a clue.
