### ISSUE TITLE
Implement parsing of Unicode math into Formula

### ISSUE THREAD

**Issue by ronaldtse** [plurimath/plurimath#32]
The plurimath gem should implement the functionality of parsing Unicode math into a Formula:

Please refer to the code in the [html2asciimath](https://github.com/plurimath/html2asciimath) and the [unitsml](https://github.com/unitsml/unitsml) gems.

**Comment by suleman-uzair** [comment]
@ronaldtse 
For Unicode conversion, can we use HTMLEntities since we will only need to encode and decode the input/output ?
It will be really helpful if you can provide some/main examples before I start.

**Comment by ronaldtse** [comment]
@suleman-uzair let's hold off UnicodeMath for now. Let's just keep this ticket for the future. Thanks.

**Comment by ronaldtse** [comment]
Closing this in favor of #31
