### ISSUE TITLE
Integrate with unitsml gem to support UnitsML

### ISSUE THREAD

**Issue by ronaldtse** [plurimath/plurimath#33]
We need to support handling of UnitsML, but the method of integration is not yet clear.

**Comment by suleman-uzair** [comment]
@ronaldtse 

I have been looking into unitsml and used the asciimath2unitsml gem to understand how the input of unitsml will be received from the user. But I’m unable to find anything related to parsing/transformation rules.
Can you point me to some examples of how the input and output will look to help me better understand the flow?

**Comment by ronaldtse** [comment]
You can see some of the usage in the README: https://github.com/plurimath/asciimath2unitsml#usage

> Dimensions are automatically inserted corresponding to each unit. Units expressions are identified in MathML as `<mtext>unitsml(…​)</mtext>`, which in turn can be identified in AsciiMath as `"unitsml(…​)"`.

```ruby
c.Asciimath2UnitsML('1 "unitsml(mm*s^-2)"') # AsciiMath string containing UnitsML
```

This is an AsciiMath representation that contains a UnitsML statement inside.
* The AsciiMath string is `1 "unitsml(mm*s^-2)"`
* The UnitsML string is `unitsml(mm*s^-2)`. The double quotes ("...") indicate in AsciiMath that it is text, and not to process it.
* The `Asciimath2UnitsML` methods renders the AsciiMath string using AsciiMath, resulting in a MathML XML string with the UnitsML string embedded. (https://github.com/plurimath/asciimath2unitsml/blob/2f1d2a5716997bbfe917dfa2e1ed527893e84a8e/lib/asciimath2unitsml/parse.rb#L115)
* Then it processes the MathML XLM string which contains the UnitsML string, and converts the UnitsML string into UnitsML XML. (https://github.com/plurimath/asciimath2unitsml/blob/2f1d2a5716997bbfe917dfa2e1ed527893e84a8e/lib/asciimath2unitsml/parse.rb#L122)

What we need to do:
* Extract UnitsDB usage from asciimath2unitsml to unitsml-ruby
    * [ ] https://github.com/unitsml/unitsml-ruby/issues/1
    * [ ] https://github.com/unitsml/unitsml-ruby/pull/3
* Refactor https://github.com/plurimath/asciimath2unitsml
    * [ ] https://github.com/plurimath/asciimath2unitsml/issues/9
    * [ ] https://github.com/plurimath/asciimath2unitsml/issues
* Use plurimath
    * [ ] https://github.com/plurimath/asciimath2unitsml/issues/35

**Comment by suleman-uzair** [comment]
@ronaldtse ,

> What we need to do:
>
>   Extract UnitsDB usage from asciimath2unitsml to unitsml-ruby

I'm assuming I need to pause `plurimath` and start working on extracting UnistsDB usage from `asciimath2unitsml` to `unitsml-ruby`, right?
