### ISSUE TITLE
Provide detailed documentation on how to work with Plurimath gem

### ISSUE THREAD

**Issue by ronaldtse** [plurimath/plurimath#40]
In Metanorma we have a need to convert between MathML and LaTeX math. We would need some documentation on how to do that. Thanks!

Issue: https://github.com/metanorma/metanorma-ieee/issues/118

**Comment by ronaldtse** [comment]
Ping @suleman-uzair , @opoudjis needs this ASAP. Thanks.

**Comment by suleman-uzair** [comment]
> Ping @suleman-uzair , @opoudjis needs this ASAP. Thanks.

I have re-prioritized tasks and started working on Mathml to Latex documentation. I will try to complete this ASAP.
