### ISSUE TITLE
Plurimath parsing of MathML presupposes no namespacing

### ISSUE THREAD

**Issue by opoudjis** [plurimath/plurimath#63]
I'm putting workarounds, so this is not urgent, but:

Your code presupposes that any MathML it parses will not have namespacing, and namespace prefixes on nodes.

But of course, I will routinely want to grab a namespaced MathML node from a Metanorma document, and parse it in Plurimath. That means that what you will be seeing is:

`Plurimath::Math.parse("<m:math>\n  <m:msup> <m:mrow> <m:mo>(</m:mo> <m:mrow> <m:mi>x</m:mi> <m:mo>+</m:mo> <m:mi>y</m:mi> </m:mrow> <m:mo>)</m:mo> </m:mrow> <m:mn>2</m:mn> </m:msup>\n</m:math>"", "mathml")`

(where the `m:` prefix is defined in the document root, but doesn't necessarily make it into the XML string, depending on how I invoke it.)

And Plurimath can't cope with those node prefixes:

````
     Parslet::ParseFailed:
       Failed to match sequence ('<' (open:'annotation-xml' / open:'annotation_xml' / open:'mmultiscripts' / open:'maligngroup' / open:'malignmark' / open:'annotation' / open:'munderover' / open:'mscarries' / open:'semantics' / open:'mphantom' / open:'mlongdiv' / open:'menclose' / open:'mscarry' / open:'msubsup' / open:'mpadded' / open:'maction' / open:'msgroup' / open:'mfenced' / open:'merror' / open:'munder' / open:'mtable' / open:'mstyle' / open:'mstack' / open:'mspace' / open:'msline' / open:'mfrac' / open:'mover' / open:'msrow' / open:'mroot' / open:'msqrt' / open:'msup' / open:'msub' / open:'mrow' / open:'math' / open:'mtr' / open:'mtd' / open:'ms' / open:'mi' / open:'mo' / open:'mn') attributes:((name:([a-zA-Z]{0, }) '=' ('"' value:([^\"]{0, }) '"' / ''' value:([^']{0, }) ''')){0, }) '>' iteration:ITERATION '<' '/' (close:'annotation-xml' / close:'annotation_xml' / close:'mmultiscripts' / close:'maligngroup' / close:'malignmark' / close:'annotation' / close:'munderover' / close:'mscarries' / close:'semantics' / close:'mphantom' / close:'mlongdiv' / close:'menclose' / close:'mscarry' / close:'msubsup' / close:'mpadded' / close:'maction' / close:'msgroup' / close:'mfenced' / close:'merror' / close:'munder' / close:'mtable' / close:'mstyle' / close:'mstack' / close:'mspace' / close:'msline' / close:'mfrac' / close:'mover' / close:'msrow' / close:'mroot' / close:'msqrt' / close:'msup' / close:'msub' / close:'mrow' / close:'math' / close:'mtr' / close:'mtd' / close:'ms' / close:'mi' / close:'mo' / close:'mn') '>') at line 1 char 2.
````

I am stripping the `m:` prefixes by regex before calling Plurimath.parse. I shouldn't have to: either you strip them on receipt, or you allow optional prefixes on all element names.

**Comment by ronaldtse** [comment]
This is exactly why Plurimath needs to take a proper XML approach for MathML parsing.

Given this is done for OMML, we need to also update the approach with MathML parsing.

**Comment by ronaldtse** [comment]
This task also depends on #75 .
