### ISSUE TITLE
Recognizing Greek letters in latexmath

### ISSUE THREAD

**Issue by ronaldtse** [plurimath/plurimath#83]
Reported by @anermina at https://github.com/plurimath/latexmath/issues/41

Latexmath doesn't recognize all Greek letters as arguments.

Example:
````
[latexmath%unnumbered]
++++
\vec{\tau} + \hat{\lambda} + \tilde{\mu} + \bar{\gamma}
++++
````

![image](https://user-images.githubusercontent.com/55683568/164557093-a5fe6aa2-8ab6-4a3b-bf08-dbb79fe9709a.png)

_Originally posted in https://github.com/metanorma/iso-10303-detached-docs/issues/109_

**Comment by suleman-uzair** [comment]
@ronald This is an issue in the Latexmath gem.
I have verified that this issue does not exist in Plurimath/Plurimath.

**Comment by ronald** [comment]
@ronaldtse

**Comment by ronaldtse** [comment]
(Thank you @ronald !)

Thanks @suleman-uzair !
