### ISSUE TITLE
Copy rspec from latexmath gem, including the setup for checking against LaTeXML

### ISSUE THREAD

**Issue by ronaldtse** [plurimath/plurimath#87]
1. In the latexmath gem we created a number of specs that need to be moved over here.
2. In the latexmath gem, we use the LaTeXML Perl module as the "reference converter" for LaTeX math to MathML. i.e. the output of latexmath conversion should always be identical to LaTeXML. We need to move those tests over also from the latexmath gem.

**Comment by ronaldtse** [comment]
@suleman-uzair any questions on this task?

**Comment by suleman-uzair** [comment]
> @suleman-uzair any questions on this task?

@ronaldtse From what I understand we need to copy specs from latexmath to plurimath. Is this correct?

**Comment by ronaldtse** [comment]
Yes that's correct. We also need to copy the LaTeXML spec setup here to validate the LaTeX => MathML output.

[LaTeXML](https://github.com/brucemiller/LaTeXML) is a Perl implementation of LaTeX Math to MathML conversion by Bruce Miller at NIST, used in NIST's digital math program, and we need to use it as our reference conversion target.

**Comment by suleman-uzair** [comment]
> 1. In the latexmath gem we created a number of specs that need to be moved over here.

This point is complete in [PR](https://github.com/plurimath/plurimath/pull/102).

> 2. In the latexmath gem, we use the LaTeXML Perl module as the "reference converter" for LaTeX math to MathML. i.e. the output of latexmath conversion should always be identical to LaTeXML. We need to move those tests over also from the latexmath gem.

Started working on the second point.

**Comment by ronaldtse** [comment]
Thanks @suleman-uzair , once the second point is done we can close this issue.
